### PR TITLE
Adding Validatus Services 

### PR DESCRIPTION
**Pull request by Validatus**
This pull request includes the addition of Validatus service links, such as RPC endpoints, seed nodes, namadillo, snapshots, indexer, masp-indexer.

### CODE REVIEW

**Comment by Crypto-Druide** [comment]
Hello @Validatus ,
Thanks for your support !
I noticed that you created new entries for your seed and peer addresses, even though they were already in the files.
Since I can't edit your files and your new entries are correct, could you please update your PR to remove the previous entries?
Thank you and have a nice day.

**Comment by Validatus** [comment]
> I noticed that you created new entries for your seed and peer addresses, even though they were already in the files.
That's perfect, you're absolutely right. Thank you for pointing that out! Let's stay strong together! 😊

**Comment by Validatus** [comment]
Thanks for the hint. 
Next time I'll definitely use my IDE - maybe it can also proofread my life decisions while we're at it! 🤖

And let's don't forget: Brackets are like relationships - they need a proper closure!
Thanks @Crypto-Druide

**Comment by Crypto-Druide** [comment]
Hey @Validatus 
I'm sorry to ask you again, but the structure is not correct in the other files.
Could you please check and make the necessary corrections?
Thank you and have a nice day.

**Comment by Validatus** [comment]
Updated JSON files. Thanks again!

**Comment by Validatus** [comment]
We are implementing a linter now as well.

**Comment by Validatus** [comment]
Not my day at all.... @Crypto-Druide!
Thanks...

**Comment by Validatus** [comment]
When Errors Persist - Punish Me! Close the PR and I will redo all of it. 

Thanks @Crypto-Druide

**Comment by Validatus** [comment]
Thanks @Crypto-Druide

**Pull request merged**
